# Generated by Django 4.2.7 on 2025-07-17 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=100, unique=True)),
                ('game_mode', models.CharField(max_length=50)),
                ('game_type', models.CharField(max_length=50)),
                ('queue_id', models.IntegerField()),
                ('game_duration', models.IntegerField(help_text='Game duration in seconds')),
                ('game_creation', models.BigIntegerField(help_text='Unix timestamp')),
                ('platform_id', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-game_creation'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riot_id', models.CharField(blank=True, help_text="Riot ID (e.g., 'SummonerName#TAG')", max_length=100)),
                ('puuid', models.CharField(blank=True, help_text='Riot PUUID', max_length=100)),
                ('summoner_name', models.CharField(blank=True, max_length=100)),
                ('tag_line', models.CharField(blank=True, max_length=10)),
                ('region', models.CharField(default='na1', max_length=10)),
                ('last_match_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riot_id', models.CharField(help_text="Riot ID (e.g., 'SummonerName#TAG')", max_length=100)),
                ('puuid', models.CharField(help_text='Riot PUUID', max_length=100, unique=True)),
                ('summoner_name', models.CharField(max_length=100)),
                ('tag_line', models.CharField(max_length=10)),
                ('region', models.CharField(default='na1', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['summoner_name'],
                'unique_together': {('user', 'puuid')},
            },
        ),
        migrations.CreateModel(
            name='AnalysisTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tile name for identification', max_length=100)),
                ('match_filter', models.CharField(choices=[('exact', 'Exact Match - Only include matches with exactly these players'), ('inclusive', 'Inclusive - Include matches with these players plus others')], default='inclusive', help_text='How to filter matches for this tile', max_length=10)),
                ('include_self', models.BooleanField(default=True, help_text='Whether to include the user in the analysis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('friends', models.ManyToManyField(related_name='analysis_tiles', to='core.friend')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_tiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puuid', models.CharField(max_length=100)),
                ('summoner_name', models.CharField(max_length=100)),
                ('champion_id', models.IntegerField()),
                ('champion_name', models.CharField(max_length=100)),
                ('team_id', models.IntegerField()),
                ('win', models.BooleanField()),
                ('kills', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('gold_earned', models.IntegerField()),
                ('total_damage_dealt', models.IntegerField()),
                ('total_damage_taken', models.IntegerField()),
                ('vision_score', models.IntegerField()),
                ('cs', models.IntegerField(help_text='Creep score')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.match')),
            ],
            options={
                'ordering': ['team_id', 'summoner_name'],
                'unique_together': {('match', 'puuid')},
            },
        ),
    ]
