# Generated by Django 4.2.7 on 2025-07-17 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysistile',
            name='include_self',
        ),
        migrations.AlterField(
            model_name='analysistile',
            name='match_filter',
            field=models.CharField(choices=[('exclusive', 'Exclusive - Only include matches with these friends + random players (no other friends)'), ('inclusive', 'Inclusive - Include matches with these players plus others')], default='inclusive', help_text='How to filter matches for this tile', max_length=10),
        ),
    ]
