# Generated by Django 4.2.7 on 2025-07-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_analysistile_include_self_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchparticipant',
            name='lane',
            field=models.CharField(blank=True, help_text='Player lane (e.g., TOP, JUNGLE, MIDDLE, BOTTOM, UTILITY)', max_length=20),
        ),
        migrations.AddField(
            model_name='matchparticipant',
            name='role',
            field=models.CharField(blank=True, help_text='Player role (e.g., SOLO, DUO, NONE)', max_length=20),
        ),
    ]
