# Generated by Django 4.2.7 on 2025-07-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_matchparticipant_lane_matchparticipant_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='match_count',
            field=models.IntegerField(default=50, help_text='Number of matches to fetch'),
        ),
    ]
