# Generated by Django 4.2.7 on 2025-07-18 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_friend_match_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='date_from',
            field=models.DateField(blank=True, help_text='Start date for match query (YYYY-MM-DD)', null=True),
        ),
        migrations.AddField(
            model_name='friend',
            name='date_to',
            field=models.DateField(blank=True, help_text='End date for match query (YYYY-MM-DD)', null=True),
        ),
        migrations.AddField(
            model_name='friend',
            name='total_matches_fetched',
            field=models.IntegerField(default=0, help_text='Total number of matches fetched for this friend'),
        ),
    ]
