# Generated by Django 4.2.7 on 2025-07-18 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_friend_date_from_friend_date_to_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysistile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={},
        ),
        migrations.AddField(
            model_name='analysistile',
            name='date_from',
            field=models.DateField(blank=True, help_text='Start date for match filtering (YYYY-MM-DD)', null=True),
        ),
        migrations.AddField(
            model_name='analysistile',
            name='date_to',
            field=models.DateField(blank=True, help_text='End date for match filtering (YYYY-MM-DD)', null=True),
        ),
        migrations.AddField(
            model_name='analysistile',
            name='max_matches_per_tile',
            field=models.IntegerField(default=50, help_text='Maximum number of matches to show per tile'),
        ),
        migrations.AlterField(
            model_name='analysistile',
            name='match_filter',
            field=models.CharField(choices=[('inclusive', 'Inclusive - Include matches with these players plus others'), ('exclusive', 'Exclusive - Only include matches with these friends + random players (no other friends)')], default='inclusive', max_length=20),
        ),
        migrations.AlterField(
            model_name='analysistile',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='game_creation',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='game_duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='platform_id',
            field=models.CharField(default='NA1', max_length=10),
        ),
        migrations.AlterField(
            model_name='match',
            name='queue_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['game_creation'], name='core_match_game_cr_53f454_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['match_id'], name='core_match_match_i_af5948_idx'),
        ),
    ]
