# Generated by Django 4.2.7 on 2025-09-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_analysistile_options_alter_match_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='puuid',
            field=models.CharField(help_text='Riot PUUID', max_length=100),
        ),
    ]
